language: python
python:
  - "2.7"
env:
   - PYTHONPATH=.
# command to install dependencies
install:
  - sudo apt-get install spell
  - pip install -r requirements.txt
  - pip install flake8
  - pip install pylint
  - pip install pytest
  - sh ./tests/init_config.sh
# command to run tests
script:
  - flake8 --max-line-length=100 matrigram matrigram_main.py
  - pylint --errors-only matrigram matrigram_main.py
  - py.test
after_script:
  - pylint --disable=too-many-instance-attributes,redefined-builtin,ungrouped-imports,too-many-public-methods,fixme,missing-docstring,invalid-name,protected-access matrigram matrigram_main.py
  - spell <(git log -1 --pretty=%B)
